### ISSUE TITLE
Very aggrieved,when you guys  were played by Brother Steel Basin as a monkey.

### ISSUE THREAD

**Issue by Luminometor** [hoyolife/stone#1]
When you guys  were played by Brother Steel Basin as a monkey.

**Comment by hoyolife** [comment]
好惨的一孝子，已经沦落到用翻译器来嘲讽了。你家磨轮老仙需要你去上供治郁了。

**Comment by Luminometor** [comment]
does it matter?only you guys think everything is less important than telling everyone what you have done.

**Comment by Luminometor** [comment]
one day you're dying,lying on the bed,the last word come into your mind is not your mom,not your dad,but the MIHOYO.How pathetic.

**Comment by hoyolife** [comment]
我是真心关心磨轮老仙的身体状况，他看起来似乎很伤心，因为Hoyoverse开除了他。

**Comment by hoyolife** [comment]
没啥有营养的内容，一击脱离小仙蛆，close
