### ISSUE TITLE
Nahida-Liberation-Front

### ISSUE THREAD

**Issue by asakayaha** [hoyolife/stone#4]
https://github.com/asakayaha/Nahida-Liberation-Front
很早之前的Nahida-Liberation-Front，但内容很少，也不符合发帖规范，但里面的一些可能恶心的东西实在不想再看一遍了。随缘过审吧。

**Comment by hoyolife** [comment]
收到，稍后合并一起。

**Comment by hoyolife** [comment]
已经合并，[原神须弥二创合集](https://github.com/hoyolife/stone/tree/main/%E5%AD%98%E6%A1%A3/%E6%96%87%E7%AB%A0/%E5%8E%9F%E7%A5%9E%E9%A1%BB%E5%BC%A5%E4%BA%8C%E5%88%9B%E5%90%88%E9%9B%86)，关闭此项。
