### ISSUE TITLE
可以接受这样的pr吗?

### ISSUE THREAD

**Issue by jqtmviyu** [hoyolife/stone#5]
https://github.com/jqtmviyu/HOYOLIFE

结构变动有点大, 不行的话我再研究下submodules

**Comment by jqtmviyu** [comment]
这是用 submodules, https://github.com/jqtmviyu/hoyolifepage
可能还需要写个更新, 但增加了复杂度

**Comment by hoyolife** [comment]
图片后缀无需修改，图片路径已修改，感谢指正。

**Comment by jqtmviyu** [comment]
> 图片后缀无需修改，图片路径已修改，感谢指正。

![image](https://github.com/hoyolife/stone/assets/19925192/ba42068d-fc10-4241-bd08-2d030909c9de)

原来是大写, mardown中引用是小写. 在vitepress中是会识别错误的.
